---
name: MultiPlayerCounter
main: davidglitch04\MultiPlayerCounter\Main
src-namespace-prefix: davidglitch04\MultiPlayerCounter
api: 4.0.0
version: 0.0.4
author: DavidGlitch04
website: https://github.com/DavidGlitch04
load: STARTUP
description: "A PocketMine-MP plugin that combines online players counts of multiple servers."
extensions:
  core: ">=8.0"

permissions:
  multiplayercount.allow.command:
    default: op
    description: "Allow player to use /multiplayercount command"
...
